### ISSUE TITLE
Last arrow color slightly off?

### ISSUE THREAD

**Issue by claymcleod** [caiogondim/bullet-train-oh-my-zsh-theme#118]
Hey @caiogondim,

Just bringing this to your attention --- wondering if this is a product of the font I'm using or the system configuration:

<img width="604" alt="screen shot 2016-02-25 at 10 55 10 pm" src="https://cloud.githubusercontent.com/assets/3411613/13343551/37de5ab8-dc13-11e5-98bc-87af74d601a1.png">

See how the last arrow is slightly discolored? That just bugs me.

Oddly enough, that behavior only happens for the last arrow:

<img width="343" alt="screen shot 2016-02-25 at 10 56 57 pm" src="https://cloud.githubusercontent.com/assets/3411613/13343549/33497140-dc13-11e5-917b-71ed320343f1.png">

FYI, I'm using Source Code Pro for Powerline. What font are you using?

**Comment by dhayab** [comment]
Hi, I also had this problem, and in my case it was fixed by reducing the window transparency in my terminal settings until the colors matched.

**Comment by caiogondim** [comment]
Transparency is only applied to background colours, not to foreground.
This can also help you: https://github.com/caiogondim/bullet-train-oh-my-zsh-theme/issues/90

Let us know if you need more help.

**Comment by vadviktor** [comment]
Is it a Mac related issue? I am certainly not experiencing it in any of my Linux terminals, with or without  transparency applied.

**Comment by caiogondim** [comment]
Guess it is related to the shell application you are using.
I'm closing this issue.

You can reopen if it is not clear.

Cheers.

**Comment by srrvnn** [comment]
i see this issue while using Terminal.app. and changing transparency increases the difference in color for the Tomorrow Night Eighties theme. any luck fixing this once and for all?

**Comment by alexcowell** [comment]
@srrvnn I also had this issue with Terminal.app.

The fix is to set an explicit background colour for the last arrow, although please note that this will only work if the terminal background is set to 100% opacity, otherwise it will look weird.

I modified the `prompt_end()` function in `bullet-train.zsh-theme` like so:

```zsh
prompt_end() {
  if [[ -n $CURRENT_BG ]]; then
    echo -n " %{%K{$BULLETTRAIN_PROMPT_BG}%F{$CURRENT_BG}%}$SEGMENT_SEPARATOR%{%k%}"
  else
  ...
}
```

What this does is, for the final prompt arrow, set the background colour to `BULLETTRAIN_PROMPT_BG`, then reset afterwards.

Simply set `BULLETTRAIN_PROMPT_BG` in your `.zshrc` to the ANSI colour code of your background theme and you should be good to go!

For example, in my case the prompt looked like this:

![image](https://user-images.githubusercontent.com/1070490/32955814-f55ed52c-cbae-11e7-81f3-28d53e59194b.png)

After applying the above fix to the theme and setting `BULLETTRAIN_PROMPT_BG=15` in my `.zshrc` my prompt now looks like this:

![image](https://user-images.githubusercontent.com/1070490/32955867-18e1be56-cbaf-11e7-9fea-ffdb3e0d4874.png)

**Comment by CodeCommander** [comment]
Any reason to not make this change in the default bullet-train.zsh-theme file?
