### ISSUE TITLE
Extra powerline character

### ISSUE THREAD

**Issue by mike3run** [caiogondim/bullet-train-oh-my-zsh-theme#185]
I have no idea why I'm getting this blue powerline triangle on top of every line has anyone had this issue with this theme?

![captura de pantalla 2016-12-31 a la s 16 11 30](https://cloud.githubusercontent.com/assets/7088511/21579426/e6822d52-cf73-11e6-91ab-921c2a4dcae4.png)

**Comment by sfarzy** [comment]
If you're using iTerm2 then it's because of the [shell integration feature](https://www.iterm2.com/documentation-shell-integration.html). From their documentation

> When shell integration is enabled, iTerm2 automatically adds a mark at each command prompt. Marks are indicated visually by a small blue triangle in the left margin.
![image](https://cloud.githubusercontent.com/assets/10276208/21580087/960fa35a-cffe-11e6-8230-c29606e92045.png)
You can navigate marks with Cmd-Shift-Up and Down-arrow keys.

**Comment by mike3run** [comment]
Awesome I was able to disable that with:

https://gist.github.com/victor-torres/67c272be0cb0d6989729

Thanks a bunch!
