### ISSUE TITLE
Arrow colour issue

### ISSUE THREAD

**Issue by iamtimm** [caiogondim/bullet-train-oh-my-zsh-theme#90]
I've having some trouble with the arrow, I cant seem to get the colours to match.
I'm using the Terminal App with xterm-256color and I'm on El Capitan.

<img width="234" alt="screen shot 2015-10-29 at 20 11 23" src="https://cloud.githubusercontent.com/assets/2601332/10829267/45ee2df6-7e79-11e5-9539-279e694d88a9.png">

**Comment by caiogondim** [comment]
Guess it is related to this issue https://github.com/caiogondim/bullet-train-oh-my-zsh-theme/issues/56

**Comment by iamtimm** [comment]
@caiogondim It is but he's using iTerm and I'm using the Terminal App.

**Comment by caiogondim** [comment]
The problems seems to be on your colour scheme.
- http://apple.stackexchange.com/questions/29487/is-it-possible-to-disable-terminals-automatic-tweaking-of-colors-in-lion
- https://github.com/morhetz/gruvbox/issues/8

Seems that, on Terminal.app, it tries to be smart and changes color based on contrast.
The fix seems to be setting up the colours on your colour scheme to be HSL instead of RGB.

**Comment by caiogondim** [comment]
Let me know if you need some more help.
Glad to help.

**Comment by Snger** [comment]
Hi, @caiogondim ,
I had read follow links:

* http://apple.stackexchange.com/questions/29487/is-it-possible-to-disable-terminals-automatic-tweaking-of-colors-in-lion
* [morhetz/gruvbox#8](https://github.com/morhetz/gruvbox/issues/8)

But didn't find where to 
> setting up the colours on your colour scheme to be HSL instead of RGB

in mac terminal setting.

![image](https://cloud.githubusercontent.com/assets/1173747/12022207/8fac60ee-ad85-11e5-9fb2-e05d2a89fff4.png)

**Comment by haf** [comment]
Set "Keep background colours opaque" 
<img width="292" alt="image" src="https://user-images.githubusercontent.com/193115/100546541-2e4e4f80-3262-11eb-8ff1-a26e32e55dfd.png">
